# Generated by Django 6.0.2 on 2026-05-04 04:22

import ckeditor.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('title', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('dec', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
