# Generated by Django 6.0.2 on 2026-05-04 09:15

import ckeditor.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_logomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialsModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('title', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('dec', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='Testimonials/')),
            ],
        ),
    ]
